alias ls='lsd'
alias grep='rg'
alias cat='bat'
alias less='bat'
alias df='duf'
alias du='dua'
alias find='fd'
alias zzz='systemctl suspend'
alias free='free -h'
alias lstrash='trash-list'
alias untrash='trash-restore'
alias purgetrash='trash-empty -f --all-users'
alias inxi="inxi -c11"
alias tty-clock='tty-clock -C3 -c -s -n -f "%A %d %B %Y (%Z)"'
alias mpc="mpc -f '%position%. %Artist% %performer% - %title% (%Album% %date%)'"
alias nnn='n'
alias edit=nvim
alias vim=nvim
alias vimdiff='nvim -d'
alias git-pull-all='\find . -maxdepth 3 -name .git -type d | rev | cut -c 6- | rev | xargs -I {} git -C {} pull' #pull all repos up to level 3 dir, at once.
alias makepkg-install-clean='makepkg -sric'
alias flatinstall='flatpak install --user'
alias flatupdate='flatpak update --user'
alias flatpurge='flatpak uninstall --delete-data --user'
alias flatlist='flatpak list --app'
alias flatlistall='flatpak list'
alias flatclean='flatpak uninstall --unused --user'
alias flatfix='flatpak repair --user'
alias mpd-notification="mpd-notification -H localhost -p 6600 -m $XDG_MUSIC_DIR -s 150 -t 10 & disown"
alias easyeffects-daemon='flatpak run com.github.wwmm.easyeffects --gapplication-service & disown'
alias pacclean='pacman -Qtdq | sudo pacman -Rns - ; pacman -Qqd | sudo pacman -Rsu -'
alias nmount='$HOME/.config/nnn/plugins/nmount'
alias mtpmount='$HOME/.config/nnn/plugins/mtpmount'
